server {
    listen 80;
    listen [::]:80;

    server_name portfolio.109-248-18-117.sslip.io;

    root /var/www/portfolio/current;
    index index.html;

    access_log /var/log/nginx/portfolio.access.log;
    error_log /var/log/nginx/portfolio.error.log;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|png|jpe?g|gif|svg|webp|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name tenroman.com www.tenroman.com;
    root /var/www/portfolio/current;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        return 301 https://tenroman.com$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name www.tenroman.com;

    ssl_certificate /etc/letsencrypt/live/tenroman.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tenroman.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://tenroman.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name tenroman.com;

    root /var/www/portfolio/current;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/tenroman.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tenroman.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/portfolio.access.log;
    error_log /var/log/nginx/portfolio.error.log;

    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|png|jpe?g|gif|svg|webp|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }
}
